// CoursesData.js

const CoursesData = [

    {
        id: 1,
        groupID: 'Afsætning',
        education: 'HHX',
        title: 'Afsætning A',
        titleKey: 'id1CourseName',
        started: true,
        progress: 50,
        mastery: 40,
        pointsEarned: 1000,
        exercises: 10
    },
    {
        id: 2,
        groupID: 'Afsætning',
        education: 'HHX',
        title: 'Afsætning B',
        titleKey: 'id2CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 3,
        groupID: 'Dansk',
        education: 'HHX',
        title: 'Dansk A',
        titleKey: 'id3CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 4,
        groupID: 'Engelsk',
        education: 'HHX',
        title: 'Engelsk A',
        titleKey: 'id4CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 5,
        groupID: 'Erhvervsjura',
        education: 'HHX',
        title: 'Erhvervsjura B',
        titleKey: 'id5CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 6,
        groupID: 'Erhvervsjura',
        education: 'HHX',
        title: 'Erhvervsjura C',
        titleKey: 'id6CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 7,
        groupID: 'Finansiering',
        education: 'HHX',
        title: 'Finansiering B',
        titleKey: 'id7CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 8,
        groupID: 'Fransk',
        education: 'HHX',
        title: 'Fransk Fortsættersprog A',
        titleKey: 'id8CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 9,
        groupID: 'Fransk',
        education: 'HHX',
        title: 'Fransk Fortsættersprog B',
        titleKey: 'id9CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 10,
        groupID: 'Fransk',
        education: 'HHX',
        title: 'Fransk Begyndersprog A',
        titleKey: 'id10CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 11,
        groupID: 'Historie',
        education: 'HHX',
        title: 'Historie B',
        titleKey: 'id11CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 12,
        groupID: 'International Økonomi',
        education: 'HHX',
        title: 'International Økonomi A',
        titleKey: 'id12CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 13,
        groupID: 'International Økonomi',
        education: 'HHX',
        title: 'International Økonomi B',
        titleKey: 'id13CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 14,
        groupID: 'Matematik',
        education: 'HHX',
        title: 'Matematik A',
        titleKey: 'id14CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 15,
        groupID: 'Matematik',
        education: 'HHX',
        title: 'Matematik B',
        titleKey: 'id15CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 16,
        groupID: 'Matematik',
        education: 'HHX',
        title: 'Matematik C',
        titleKey: 'id16CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 17,
        groupID: 'Samfundsfag',
        education: 'HHX',
        title: 'Samfundsfag C',
        titleKey: 'id17CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 18,
        groupID: 'Spansk',
        education: 'HHX',
        title: 'Spansk Fortsættersprog A',
        titleKey: 'id18CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 19,
        groupID: 'Spansk',
        education: 'HHX',
        title: 'Spansk Fortsættersprog B',
        titleKey: 'id19CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 20,
        groupID: 'Spansk',
        education: 'HHX',
        title: 'Spansk Begyndersprog A',
        titleKey: 'id20CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 21,
        groupID: 'Tysk',
        education: 'HHX',
        title: 'Tysk Fortsættersprog A',
        titleKey: 'id21CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 22,
        groupID: 'Tysk',
        education: 'HHX',
        title: 'Tysk Fortsættersprog B',
        titleKey: 'id22CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 23,
        groupID: 'Tysk',
        education: 'HHX',
        title: 'Tysk Begyndersprog A',
        titleKey: 'id23CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 24,
        groupID: 'Virksomhedsøkonomi',
        education: 'HHX',
        title: 'Virksomhedsøkonomi A',
        titleKey: 'id24CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
    {
        id: 25,
        groupID: 'Virksomhedsøkonomi',
        education: 'HHX',
        title: 'Virksomhedsøkonomi B',
        titleKey: 'id25CourseName',
        started: false,
        progress: 0,
        mastery: 0,
        pointsEarned: 0,
        exercises: 0
    },
// Add more course objects here
];

export default CoursesData;